### ISSUE TITLE
Suggestion: Config to set protection level of all horse armor?

### ISSUE THREAD

**Issue by Guinaro** [Craftjakob/Netherite-Horse-Armor-CJ#1]
Would it be possible to provide configuration options to set each horse armor's protection level.
This for the armors provided by your mod, aswell as that from minecraft itself:
leather, gold, iron and diamond.
Thanks in advance,
Guinaro

**Comment by Craftjakob** [comment]
Sorry for the late reply, I wasn't at home this week.
A setting for the protection value of the mod horse armors is possible, but for the Minecraft horse armors it is more difficult. I'll put it on my to-do list, but I can't promise anything.

Thanks for your feedback!

**Comment by Craftjakob** [comment]
Now you can set the mod horse armor values, because of Config API.
